export const routes = {
  Home: 'Home',
  HomeFeed: 'HomeFeed',
  Pricing: 'Pricing',
  LabDocket: 'LabDocket',
  RecordList: 'Patient Record',
  CreateRecord: 'Create Record',
  CreateTransportRequest: 'Create Transport Request',
  RecordInquriy: 'Record Inquiry',
  TransportList: 'Pickup List',
  Auth: 'Auth',
  UserSignIn: 'UserSignin',
  UserSignUp: 'UserSignup',
  UpdateUser: 'UpdateUser',
  ConfirmPassword: 'ConfirmPassword',
  ImagePicker: 'ImagePicker',
  Pin: 'PinScreen',
  PasswordReset: 'PasswordReset',
  Email: 'Email',
  PreviewCarousel: 'PreviewCarousel',
  PreviewRecord: 'PreviewRecord',
  ImagePreview: 'ImagePreview',
  Logout: 'Logout',
  ChatRoomList: 'ChatRoomList',
  ChatRoom: 'ChatRoom',
  UploadPhoto: 'UploadPhoto',
  VerifyUsers:'VerifyUsers'
};
