export const routes = {
  Home: 'Home',
  SkSales: 'SkSales',
  Pricing: 'Pricing',
  LabDocket: 'LabDocket',
  RecordList: 'Patient Record',
  CreateRecord: 'Create Record',
  ArrangePickup: 'Arrange Pickup',
  RecordInquriy: 'Record Inquiry',
  PickupList: 'Pickup List',
  Auth: 'Auth',
  UserSignIn: 'UserSignin',
  UserSignUp: 'UserSignup',
  UpdateUser: 'UpdateUser',
  ConfirmPassword: 'ConfirmPassword',
  ImagePicker: 'ImagePicker',
  Pin: 'PinScreen',
  PasswordReset: 'PasswordReset',
  Email: 'Email',
};
